# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f1094b3af8790dd26c49befa41fa27dff3ecedaf0e6fa57a2b8ddecb6812b98fef167cc607c2425e85c0839464228c60552f2b1f10a6e063b96b32d97d1ef1

test:
  secret_key_base: 7332d6c2523440601b04176ef5948752313e9b7739a8c7d91cc0ae5606b558d12016ab276dec1acceaef53b098ff6e8b6b46742d5c5f531c78d535d511a3270a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
